language: go
sudo: required
go:
- 1.4
- 1.5
- 1.6
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/gin-gonic/gin
  - go get github.com/labstack/echo
  - go get github.com/go-fsnotify/fsnotify
install:
  - go get github.com/gorilla/websocket
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
